
def convert_pixel_distance_to_meters(pixel_distance,refrence_height_meters,refrence_height_pixels):
  return pixel_distance*refrence_height_meters/refrence_height_pixels

def convert_meters_to_pixel_distance(meters,refrence_height_meters,refrence_height_pixels):
  return meters*refrence_height_pixels/refrence_height_meters